language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: QlYkhbDfiOJdnXMNjqtrVxkyxHZ6SSsZO4LB6HIFwbGBLVDpvJc5xKkyQOmkfKvhqyXjtjMXclaRbTGJmvMbbAcQN+c5yeEtQcQe0aQrqkq2cQTzMv4FMZh9rIUVPeSIaJq7oIwIBd7FKQDmN/GQL9x5tV7B0Xmh48NhiKR33+ykN0lp5gs1xn/c2a6ipYjQ9rw2ROk5pJlVZ+aphL7tCHQrVes/7r+6VNgf95lZqfix8bMEbGDPUyg6E5pyRUm9sa0z/Q0ghWp4HXazA3I2rRevGg8dmMmqRH0gqCm+JyUbTiX3s/3e6XPCe3QHv31UfIpbJuxPiLriLl3vrLI1DnGBNoH6Vj1HoojeHNcNVTWB7VW3jC5f3NSTJdNIRzE38kY8OdhbalXN2v1BBo40Wiy3YhHmMDOBpuW07lNy3kJeFJ/UUpSEKiCFkAIJ8f8KCBljnozGOpCwSKTcDDx1rlQz3GDq3waUVX+Ih+f/XXNAXsPLTKmI0MC1EbXRtYyRdMjoH9gT04CbNttfEi6ZfXGBcpAtL2j3t2GNvE/uB9JkC1z9cG8CYAvEAavM1jHLFZP+Mn/RHrLicFu2QuqTda4QY+5Lzso1rxqipli9Th150EOSqvMoG5/ir8q4MEQPd8veAxTcfP5Vr6cKP2TMpJuIO9Y4qgGZRESV0+2G6Q8=
  app: rocky-basin-59938
  on:
    repo: pheiselmann/genehack
